# Setup
title:        Portafolio
tagline:      Portafolio creado con on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "es"

# About/contact
author:
  name:       Francisco Silva
  url:        https://fsilvav.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
