# Setup
title:        Portafolio
tagline:      Portafolio creado con on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "es"

# About/contact
author:
  name:       Author name
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
